# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 004b88fb65db867dd64c0ba692d17b469d3dba4c7aa7847506d9caebc4c2743da0fbaf58ea49cbb8c630900d4525888b2ec17b8aef256c775f9a648dea980fcd

test:
  secret_key_base: 043fcc0f6f6d4dc0b76f6c9cc9e4d13bf2b0d1e638dd5c56e77a25861f9f04ecd93675b29f5fa572e0656ee5affc4ee53c1daad2e9a604689f4b7e93a174bd0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
